#!/bin/sh

. /etc/utils.sh

taxonomize() {
  sig="$1"
  python -c "import taxonomy; print taxonomy.identify_wifi_device('$sig')"
}

dhcpname() {
  mac="$1"
  while read -r time leasemac ip name junk; do
    if contains "$leasemac" "$mac"; then
      echo "$name"
    fi
  done </config/dhcp.leases
}


stations24=""
stations5=""
watch-dir /tmp/wifi/fingerprints | while read junk; do
  sleep 0.25
  wifi24=$(wifi show -b 2.4 2>&1)
  wifi5=$(wifi show -b 5 2>&1)

  for file in /tmp/wifi/fingerprints/*; do
    [ -e "$file" ] || continue
    contains "$file" ".tmp" && continue
    sig=$(cat "$file")
    mac=$(basename "$file")
    name=$(dhcpname "$mac")
    tax=$(taxonomize "$sig")

    if contains "$wifi24" "$mac"; then
      contains "$stations24" "$mac" && continue
      date
      echo 2.4GHz: "$name"
      echo "$tax"
      echo "$sig"
      echo
      stations24="${stations24},$mac"
    fi

    if contains "$wifi5" "$mac"; then
      contains "$stations5" "$mac" && continue
      date
      echo 5.0GHz: "$name"
      echo "$tax"
      echo "$sig"
      echo
      stations5="${stations5},$mac"
    fi
  done
done
